main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("notes.urls")),
    path("user/", include("users.urls")),
    path("summernote/", include("django_summernote.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes/urls.py
"""Defines URL patterns for notes"""

from django.urls import path
from . import views

app_name = "notes"
urlpatterns = [
    # Notes page
    path("", views.display_notes, name="display_notes"),
    # Note page
    path("note/<int:note_id>/", views.note, name="note"),
    # Like note page
    path("note/<int:note_id>/like_note", views.like_note, name="like_note"),
    # Create a new note page
    path("new_note/", views.new_note, name="new_note"),
    # Edit note page
    path("edit_note/<int:note_id>/", views.edit_note, name="edit_note"),
    # Delete note page
    path("edit_note/<int:note_id>/delete", views.delete_note, name="delete_note"),
]

users/urls.py
"""Defines URL patterns for users"""

from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    # Login page
    path("login/", views.CustomLoginView.as_view(), name="login"),
    # Registration page
    path("register/", views.register, name="register"),
    # Account page
    path("account/", views.account, name="account"),
    # Delete account page
    path("account/delete_account/", views.delete_account, name="delete_account"),
    # Logout page
    path("logout/", LogoutView.as_view(), name="logout"),
]

notes/models.py
from django.db import models
from django.contrib.auth.models import User

DEPARTMENTS = (
    ("Philosophy", "Philosophy"),
    ("Sciences", "Sciences"),
    ("Health Sciences", "Health Sciences"),
    ("Education", "Education"),
    ("Fine Arts", "Fine Arts"),
    ("Engineering", "Engineering"),
    ("Social Sciences", "Social Sciences"),
    ("Economics and Administrative Sciences", "Economics and Administrative Sciences"),
    ("Music Studies", "Music Studies"),
    ("Informatics and Telecommunications", "Informatics and Telecommunications"),
    ("Agricultural Technology", "Agricultural Technology"),
)


class Note(models.Model):
    title = models.CharField(max_length=100)
    department = models.CharField(max_length=100, choices=DEPARTMENTS, default=None)
    subject = models.CharField(max_length=100)
    content = models.TextField()
    file = models.FileField(upload_to="uploads/", null=True, blank=True)
    likes = models.ManyToManyField(User, related_name="liked_notes")
    timestamp = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def number_of_likes(self):
        return self.likes.count()

    def __str__(self):
        return self.title


class Comment(models.Model):
    note = models.ForeignKey(Note, on_delete=models.CASCADE, related_name="comments")
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.content[:10]

notes/forms.py
from django import forms
from .models import Note, Comment, DEPARTMENTS
from django_summernote.widgets import SummernoteWidget


class NoteForm(forms.ModelForm):
    title = forms.CharField(
        label="Title",
        widget=forms.Textarea(
            attrs={"class": "form-control bg-dark text-light", "rows": 1}
        ),
        required=True,
    )
    department = forms.ChoiceField(
        label="Department",
        choices=DEPARTMENTS,
        widget=forms.Select(attrs={"class": "form-control bg-dark text-light"}),
        required=True,
    )
    subject = forms.CharField(
        label="Subject",
        widget=forms.Textarea(
            attrs={"class": "form-control bg-dark text-light", "rows": 1}
        ),
        required=True,
    )
    content = forms.CharField(label="Content", widget=SummernoteWidget(), required=True)

    class Meta:
        model = Note
        fields = ["title", "department", "subject", "content", "file"]


class CommentForm(forms.ModelForm):
    content = forms.CharField(
        label="Write your comment here ",
        widget=forms.Textarea(
            attrs={"class": "form-control bg-dark text-light", "rows": 10}
        ),
        required=True,
    )

    class Meta:
        model = Comment
        fields = ["content"]

notes/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.paginator import Paginator
from django.contrib import messages
from django.conf import settings
from django.http import Http404
from django.urls import reverse
from .utils import send_comment_notification
from .forms import NoteForm, CommentForm
from .models import Note, DEPARTMENTS


def display_notes(request):
    # Retrieve selected department & search query,
    # from the query parameters
    department = request.GET.get("department")
    search_query = request.GET.get("search_query")
    notes = Note.objects.all().order_by("-timestamp")

    # Filter notes by search query in the title if provided
    if search_query:
        notes = notes.filter(title__icontains=search_query)

    # Filter notess by department if a department is selected
    if department:
        notes = notes.filter(department=department)

    paginator = Paginator(notes, 10)  # Display 10 notes per page
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)

    context = {
        "page_obj": page_obj,
        "DEPARTMENTS": DEPARTMENTS,
        "search_query": search_query,
    }
    return render(request, "notes/notes.html", context)


def note(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    comments = note.comments.all()

    # Like functionality
    liked = False
    if note.likes.filter(id=request.user.id).exists():
        liked = True
    number_of_likes = note.number_of_likes()

    if request.method == "POST":
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.user = request.user
            new_comment.note = note
            new_comment.save()
            note_url = reverse("notes:note", args=[note.id])
            if not settings.DEBUG and new_comment.user != note.user:
                send_comment_notification(
                    sender=new_comment.user,
                    receiver=note.user,
                    note_url=note_url,
                    comment=new_comment,
                )
            return redirect("notes:note", note_id=note_id)
    else:
        form = CommentForm()

    context = {
        "form": form,
        "note": note,
        "comments": comments,
        "number_of_likes": number_of_likes,
        "note_is_liked": liked,
    }
    return render(request, "notes/note.html", context)


def like_note(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    if note.likes.filter(id=request.user.id).exists():
        note.likes.remove(request.user)
    else:
        note.likes.add(request.user)

    return HttpResponseRedirect(reverse("notes:note", args=[note_id]))


@login_required
def new_note(request):
    if request.method == "POST":
        form = NoteForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            obj = form.save(commit=False)
            obj.user = request.user
            form.save()
            messages.success(request, "Note created successfully.")
            return redirect("notes:display_notes")
    else:
        form = NoteForm()

    context = {"form": form}
    return render(request, "notes/new_note.html", context)


@login_required
def edit_note(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    if note.user != request.user:
        raise Http404

    if request.method == "POST":
        form = NoteForm(instance=note, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Note modified successfully.")
            return redirect("notes:note", note_id=note_id)
    else:
        initial_data = {"title": note.title, "content": note.content}
        form = NoteForm(instance=note, initial=initial_data)

    context = {"note": note, "form": form}
    return render(request, "notes/edit_note.html", context)


@login_required
def delete_note(request, note_id):
    note = get_object_or_404(Note, id=note_id)
    if note.user != request.user:
        raise Http404
    note.delete()
    messages.success(request, "Note deleted successfully.")
    return redirect("notes:display_notes")

notes/templates/notes/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- Webpage title -->
    <title>{% block title %}{% endblock title %}</title>

    <!-- Bootstrap CSS -->
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <!-- Custom styles -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'main.css' %}">
</head>

<body>
    <!-- navbar start -->
    <nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container">
            <a class="navbar-brand" href="{% url 'notes:display_notes' %}">UOI-StudyNotes</a>

            <div class="d-flex align-items-center d-sm-none">
                <a href="https://github.com/KafetzisThomas/UOI-StudyNotes" class="btn bg-dark border me-2" target="_blank" aria-label="View source on GitHub">
                    <i class="bi bi-github"></i>
                </a>
                <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>

            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="{% url 'notes:display_notes' %}">Notes</a>
                    </li>
                    {% if request.path == '/' %}
                        <li class="nav-item">
                            <form action="{% url 'notes:display_notes' %}" class="d-flex" method="GET">
                                <!-- department filter dropdown -->
                                <select class="form-select form-select-sm ms-2 mt-1" name="department">
                                    <option value="" {% if not request.GET.department %}selected{% endif %}>All Departments</option>
                                    {% for key, value in DEPARTMENTS %}
                                        <option value="{{ key }}" {% if request.GET.department == key %}selected{% endif %}>{{ value }}</option>
                                    {% endfor %}
                                </select>

                                <!-- search field -->
                                <input class="form-control form-control-sm ms-2 mt-1" type="search" name="search_query" placeholder="Search notes..."
                                    value="{{ search_query|default:'' }}">

                                <button class="btn btn-sm btn-outline-secondary ms-2 mt-1 h-50" type="submit">Search</button>
                            </form>
                        </li>
                    {% endif %}
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        {% if request.user.is_superuser == 1 %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/new_note/' %}active{% endif %}" href="{% url 'notes:new_note' %}">New Note</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/user/account/' %}active{% endif %}" href="{% url 'users:account' %}">Account</a>
                        </li>
                        <li class="nav-item">
                            <form action="{% url 'users:logout' %}" method="POST" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="nav-link me-5">Log out</button>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="nav-link me-2 {% if request.path == '/user/login/' %}active{% endif %}" href="{% url 'users:login' %}">LOGIN</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link me-5 border-on-lg {% if request.path == '/user/register/' %}active{% endif %}" href="{% url 'users:register' %}">SIGN UP</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- navbar end -->

    <!-- github ribbon start -->
    <a href="https://github.com/KafetzisThomas/UOI-StudyNotes" class="github-corner d-none d-lg-block" target="_blank" aria-label="View source on GitHub">
        <svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true">
            <path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"/>
            <path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"/>
            <path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"/>
        </svg>
    </a>
    <style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>
    <!-- github ribbon end -->

    <main role="main" class="container">
        <div class="row justify-content-center mt-lg-5 mt-3">
            <div class="col-md-8 pb-2 mb-2">
                <!-- custom page header start -->
                {% block page_header %}{% endblock page_header %}
                <!-- custom page header end -->
            </div>
            <div class="col-md-8">
                <!-- custom content start -->
                {% block content %}{% endblock %}
                <!-- custom content end -->
            </div>
        </div>
    </main>

    <!-- footer start -->
    {% block footer %}{% endblock footer %}
    <!-- footer end -->
</body>

</html>

notes/templates/notes/edit_note.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}

{% block title %}UOI-StudyNotes - Edit Note{% endblock title %}

{% block page_header %}
    <h2>Edit Note:</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'notes:edit_note' note.id %}" method='POST' class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary w-100">Save Changes</button>
    </form>
{% endblock content %}

{% block footer %}
    <footer class="footer bg-dark text-light py-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <hr class="border-light mb-2">
                </div>
                <div class="col-md-8 text-center">
                    <p class="mt-1 mb-0">&copy; 2024 KafetzisThomas</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock footer %}

notes/templates/notes/new_note.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}

{% block title %}UOI-StudyNotes - New Note{% endblock title %}

{% block page_header %}
    <h2>New Note:</h2>
{% endblock page_header %}

{% block content %}
    <form action="{% url 'notes:new_note' %}" method='POST' class="form" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-secondary w-100">Save Note</button>
    </form>
{% endblock content %}

{% block footer %}
    <footer class="footer bg-dark text-light py-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <hr class="border-light mb-2">
                </div>
                <div class="col-md-8 text-center">
                    <p class="mt-1 mb-0">&copy; 2024 KafetzisThomas</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock footer %}

notes/templates/notes/note.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ note.title }}{% endblock title %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success text-center" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <div class="container mt-4 mb-4">
        <!-- note section -->
        <div class="card bg-dark mb-4">
            <div class="card-header align-items-center bg-dark border rounded-top mb-0">
                <h3 class="text-light mb-1">[{{ note.subject }}] {{ note.title }}</h3>
                <small class="text-muted">
                    <span class="badge bg-secondary">By: {{ note.user.username }}</span>
                    <span class="badge bg-secondary">Department: {{ note.department }}</span>
                    <span class="badge bg-secondary">Created: {{ note.timestamp|date:"d F, Y H:i" }}</span>
                </small>
            </div>
            <div class="card-body bg-dark text-light border rounded-left rounded-right rounded-bottom">
                <p class="card-text">{{ note.content|safe }}</p>
                {% if note.file %}
                    <a href="{{ note.file.url }}" download="{{ note.file.name }}">{{ note.file.name }}</a>
                {% endif %}
                <div class="d-flex float-end mt-4">
                    {% if user.is_authenticated %}
                        {% if request.user == note.user %}
                            <!-- delete button trigger modal -->
                            <button class="btn btn-outline-light me-1" type="button" data-toggle="tooltip" title="Delete Note" data-bs-toggle="modal" data-bs-target="#delete_note_modal">
                                <i class="bi bi-trash"></i>
                            </button>
                            <a href="{% url 'notes:edit_note' note.id %}" class="btn btn-outline-light me-1" data-toggle="tooltip" title="Edit Note">
                                <i class="bi bi-pencil-square"></i>
                            </a>
                        {% endif %}
                        <!-- display like button & like count -->
                        <form action="{% url 'notes:like_note' note.id %}" method="POST">
                            {% csrf_token %}
                            <button class="btn btn-outline-light me-1" type="submit" data-toggle="tooltip" title="{{ number_of_likes }} likes">
                                {% if note_is_liked %}
                                    <i class="bi bi-heart-fill"></i>
                                {% else %}
                                    <i class="bi bi-heart"></i>
                                {% endif %}
                            </button>
                        </form>
                        <button class="btn btn-outline-light comment-btn" type="button" data-toggle="tooltip" title="Comment" data-bs-toggle="collapse" data-bs-target="#CommentForm-{{ note.id }}" aria-expanded="false" aria-controls="CommentForm-{{ note.id }}">
                            <i class="bi bi-reply-fill"></i>
                        </button>
                    {% endif %}
                </div>
            </div>
        </div>

        <!-- comments section -->
        <div>
            <div class="list-group">
                {% for comment in comments %}
                    <div class="list-group-item bg-dark text-light border rounded mb-2">
                        <p class="mb-1">{{ comment.content|linebreaks }}</p>
                        <small class="text-muted">By {{ comment.user.username }} on {{ comment.timestamp|date:"d F, Y H:i" }}</small>
                    </div>
                {% empty %}
                    <p class="text-muted">No comments yet.</p>
                {% endfor %}
            </div>
        </div>

        <hr>

        <!-- comment section -->
        <div>
            <form class="collapse mt-4" id="CommentForm-{{ note.id }}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-success mt-2">Submit</button>
            </form>
        </div>

        <!-- Delete note modal start -->
        <div class="modal fade" id="delete_note_modal" tabindex="-1" aria-labelledby="delete_note_modal_label" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content bg-dark">
                    <div class="modal-header">
                        <h1 class="modal-title fs-5 text-light" id="delete_note_modal_label">Delete Note?</h1>
                        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body text-light">
                        Are you sure you want to delete this note?
                    </div>
                    <div class="modal-footer">
                        <form method="POST" action="{% url 'notes:delete_note' note.id %}">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-danger" name="action" value="delete">Yes</button>
                            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">No</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        <!-- Delete note modal end -->
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const commentBtn = document.querySelector('.comment-btn');
            commentBtn.addEventListener('click', function () {
                const targetForm = document.querySelector(this.getAttribute('data-bs-target'));
                targetForm.addEventListener('shown.bs.collapse', function () {
                    // Scroll to the form after pressing the comment button
                    targetForm.scrollIntoView({ behavior: 'smooth', block: 'start' });

                    // Focus the content field (textarea)
                    const textarea = targetForm.querySelector('textarea');
                    textarea.focus();

                }, { once: true });  // Trigger once per click, avoid duplicate event listeners
            });
        });
    </script>
{% endblock content %}

{% block footer %}
    <footer class="footer bg-dark text-light py-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <hr class="border-light mb-2">
                </div>
                <div class="col-md-8 text-center">
                    <p class="mt-1 mb-0">&copy; 2024 KafetzisThomas</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock footer %}

notes/templates/notes/notes.html
{% extends "notes/base.html" %}

{% block title %}UOI-StudyNotes{% endblock title %}

{% block page_header %}
    <h3 class="text-center">Notes Archive</h3>
    <div class="row">
        <div class="col">
            <hr class="mb-2 mt-0">
        </div>
    </div>
{% endblock page_header %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success text-center" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    {% for note in page_obj %}
        <article class="media note-section mb-4">
            <div class="media-body">
                <h2><a class="note-name" href="{% url 'notes:note' note.id %}">[{{ note.subject }}] {{ note.title }}</a></h2>
                <p class="card-text">
                    <small class="text-muted">
                        By: {{ note.user.username }} | Department: {{ note.department }} | Comments: {{ note.comments.all|length }} | Likes: {{ note.number_of_likes }} | {{ note.timestamp|date:"d F, Y H:i" }}
                    </small>
                </p>
            </div>
        </article>
    {% empty %}
        <div class="container text-center mt-3">
            <h5>There are no notes.</h5>
        </div>
    {% endfor %}
    <div class="pagination justify-content-center me-4 mt-4">
        <ul class="pagination">
            {% if page_obj %}
                {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link bg-dark text-white text-decoration-none"
                        href="?page={{ page_obj.previous_page_number }}"
                        style="outline: auto;"
                        onclick="this.blur();">
                        &lt;&lt;
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link bg-dark text-white text-decoration-none"
                        href="#"
                        style="pointer-events: none; opacity: 0.6; cursor: not-allowed; outline: none;"
                        onclick="event.preventDefault();">
                        &lt;&lt;
                        </a>
                    </li>
                {% endif %}
        
                {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link bg-dark text-white text-decoration-none"
                        href="?page={{ page_obj.next_page_number }}"
                        style="outline: auto;"
                        onclick="this.blur();">
                        &gt;&gt;
                        </a>
                    </li>
                {% else %}
                    <li class="page-item disabled">
                        <a class="page-link bg-dark text-white text-decoration-none"
                        href="#"
                        style="pointer-events: none; opacity: 0.6; cursor: not-allowed; outline: none;"
                        onclick="event.preventDefault();">
                        &gt;&gt;
                        </a>
                    </li>
                {% endif %}
            {% endif %}
        </ul>
    </div>
{% endblock content %}

{% block footer %}
    <footer class="footer bg-dark text-light py-3">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <hr class="border-light mb-2">
                </div>
                <div class="col-md-8 text-center">
                    <p class="mt-1 mb-0">&copy; 2024 KafetzisThomas</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock footer %}