main/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("notes.urls")),
    path("user/", include("users.urls")),
    path("summernote/", include("django_summernote.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
"""Defines URL patterns for users"""

from django.contrib.auth.views import LogoutView
from django.urls import path
from . import views

app_name = "users"
urlpatterns = [
    # Login page
    path("login/", views.CustomLoginView.as_view(), name="login"),
    # Registration page
    path("register/", views.register, name="register"),
    # Account page
    path("account/", views.account, name="account"),
    # Delete account page
    path("account/delete_account/", views.delete_account, name="delete_account"),
    # Logout page
    path("logout/", LogoutView.as_view(), name="logout"),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
        label="Username",
        widget=forms.Textarea(
            attrs={"class": "form-control bg-dark text-light", "rows": 1}
        ),
        required=True,
    )
    email = forms.CharField(
        label="Email Address",
        widget=forms.EmailInput(attrs={"class": "form-control bg-dark text-light"}),
        required=True,
    )
    password1 = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={"class": "form-control bg-dark text-light"}),
        required=True,
    )
    password2 = forms.CharField(
        label="Confirm Password",
        widget=forms.PasswordInput(attrs={"class": "form-control bg-dark text-light"}),
        required=True,
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean_email(self):
        allowed_domains = [
            "uoi.gr",
            "gmail.com",
            "apple.com",
            "outlook.com",
        ]
        email = self.cleaned_data.get("email")
        domain = email.split("@")[-1]
        if domain not in allowed_domains:
            raise ValidationError(
                "Email domain is not allowed. Please use a valid email address."
            )
        return email


class CustomAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        label="Username",
        widget=forms.Textarea(
            attrs={"class": "form-control bg-dark text-light", "rows": 1}
        ),
        required=True,
    )
    password = forms.CharField(
        label="Password",
        widget=forms.PasswordInput(attrs={"class": "form-control bg-dark text-light"}),
        required=True,
    )


class UpdateUserForm(forms.ModelForm):
    username = forms.CharField(
        label="Username",
        widget=forms.Textarea(
            attrs={"class": "form-control bg-dark text-light", "rows": 1}
        ),
        required=True,
    )
    email = forms.CharField(
        label="Email Address",
        widget=forms.EmailInput(attrs={"class": "form-control bg-dark text-light"}),
        required=True,
    )
    password1 = forms.CharField(
        label="New Password",
        widget=forms.PasswordInput(attrs={"class": "form-control bg-dark text-light"}),
        required=False,
    )
    password2 = forms.CharField(
        label="Confirm New Password",
        widget=forms.PasswordInput(attrs={"class": "form-control bg-dark text-light"}),
        required=False,
    )

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def clean(self):
        cleaned_data = super().clean()
        password1 = cleaned_data.get("password1")
        password2 = cleaned_data.get("password2")

        if password1 and password1 != password2:
            self.add_error("password2", "Passwords do not match.")

        if password1:
            try:
                validate_password(password1)
            except ValidationError as e:
                self.add_error("password1", e)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data.get("email")
        password = self.cleaned_data.get("password1")
        if password:
            user.set_password(password)
        if commit:
            user.save()
        return user

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm, CustomAuthenticationForm, UpdateUserForm
from django.contrib.auth.views import LoginView
from .utils import send_update_account_notification
from django.contrib.auth.models import User
from django.conf import settings
from django.contrib import messages


def register(request):
    """
    Register a new user.
    """
    if request.method == "POST":
        form = CustomUserCreationForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("users:login")
    else:
        form = CustomUserCreationForm()

    context = {"form": form}
    return render(request, "registration/register.html", context)


def account(request):
    if request.method == "POST":
        form = UpdateUserForm(instance=request.user, data=request.POST)
        user = User.objects.get(id=request.user.id)
        if form.is_valid():
            form.save()
            send_update_account_notification(user) if not settings.DEBUG else None
            update_session_auth_hash(request, request.user)  # Keep user logged in
            messages.success(
                request, "Your account credentials have been successfully updated."
            )
            return redirect("users:account")
    else:
        form = UpdateUserForm(instance=request.user)

    context = {"form": form}
    return render(request, "users/account.html", context)


@login_required
def delete_account(request):
    user = User.objects.get(id=request.user.id)
    user.delete()
    messages.error(
        request, "Your account has been deleted along with all associated data."
    )
    return redirect("users:register")


class CustomLoginView(LoginView):
    authentication_form = CustomAuthenticationForm

users/templates/users/account.html
{% extends "notes/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}Account Settings{% endblock title %}

{% block page_header %}
    <h2>Your account settings.</h2>
{% endblock page_header %}

{% block content %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-success text-center" role="alert">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}

    <form method="POST" action="{% url 'users:account' %}">
        {% csrf_token %}
        {{ form|crispy }}
        <button name="submit" class="btn btn-primary"><i class="bi bi-floppy"></i> Save changes</button>
        <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete_account_modal" role="button"><i class="bi bi-trash"></i> Delete account</a>
        <input type="hidden" name="next" value="{% url 'users:account' %}" />
    </form>

    <!-- Delete account modal start -->
    <div class="modal fade" id="delete_account_modal" tabindex="-1" aria-labelledby="delete_account_modal_label" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content bg-dark">
                <div class="modal-header">
                    <h1 class="modal-title fs-5 text-light" id="delete_account_modal_label">DELETE ACCOUNT</h1>
                    <button type="button" class="btn-close btn-close-white" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body text-light">
                    Procceed below to delete your account and all associated data. Deleting your account is permanent. It cannot be undone.
                </div>
                <div class="modal-footer">
                    <a class="btn btn-danger" href="{% url 'users:delete_account' %}" role="button">Delete account</a>
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Delete account modal end -->
{% endblock content %}

{% block footer %}
    <footer class="footer bg-dark text-light py-3 fixed-bottom">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-8">
                    <hr class="border-light mb-2">
                </div>
                <div class="col-md-8 text-center">
                    <p class="mt-1 mb-0">&copy; 2024 KafetzisThomas</p>
                </div>
            </div>
        </div>
    </footer>
{% endblock footer %}